# Version 1
# machine:
#   service:
#     - docker

# dependencies:
#   override:
#     - docker build -t Ejemplo

# test:
#   override:
#     - docker run Ejemplo npm test

version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.1-ce
      - image: node:8.11.1

    steps:
      - checkout

      -run: docker build -t Ejemplo -f /Dockerfile

      # run tests!
      -run: docker run Ejemplo npm test

      -run: sh deployments/qa.sh
      
    branches:
      only: /feature_.*/